cevoaustralia/cevoaustralia.github.io

- _data/testimonials.yml
The voice interface design testamonial
> dw voiceid testimonial

- _data/testimonials.yml
Ordered from urbanise, REA, VID, Monash, Aconex then MYOB.
> Re-order testimonials

- _posts/2016-11-24-Enterprise-AWS.md
> some wording

- _posts/2016-11-24-Enterprise-AWS.md
Merge in @davidw-cevo changes..
> Enterprise aws blogpost

- _data/staff.yml
Whilst looking at this PR - check out this image :)
!(I have no idea what I'm doing)[http://i2.kym-cdn.com/photos/images/original/000/234/739/fa5.jpg]
> First commit to the cevo site - with my twitter link

- _data/staff.yml
Updated Nikita's blurb to improve readability
> updated Nikita's blurb

- _posts/2015-05-03-The-Consul-of-Elders.markdown
- _posts/2015-07-09-whats-this-docker-thing.markdown
- _posts/2015-09-06-Is-the-EC2-Container-Service-a-bad-idea.markdown
- _posts/2015-09-28-My-DevOps-Journey.markdown
- _posts/2015-12-09-automated-provisioning-with-docker.markdown
- _posts/2016-08-08-migrating-to-aws.markdown
- _posts/2016-08-12-Census-2.0.markdown
- _posts/2016-08-19-girls-in-tech.markdown
- _posts/2016-11-24-Enterprise-AWS.md
**summary:** Added twitter description card meta-data to all the blog posts
**Impact:** This means when URL for a blogpost is shared via twitter the tweet will appear as a twitter card with the cevo logo as well as a one line description
**how to test it**
Copy the URL of any blog post and copy it into the twitter card validator. 
https://cards-dev.twitter.com/validator
Below is an example: 
.
> Added twitter description meta-data to blog posts

- _config.yml
- _data/open-source.yml
- _data/social.yml
- _data/testimonials.yml
added link to cevo youtube channel. 
It appears as an icon on the website now. 
Please verify!
> added link to cevo youtube channel

- _data/staff.yml
> Removing Vee

- _posts/2017-03-12-four-values-of-devops.markdown
This post aims to introduce 4 key devops values that I have been collecting.
Want to make sure we are all happy with these values.
> New blog post

- _data/staff.yml
I'm just fixing punctuation and grammar.
> tiny fixes to Shreya's profile text

- _posts/2017-08-24-devops-and-empathy.markdown
Hi ya'll, can I please get some eyes on this PR. I'd like to :shipit: as quick as I can.
> redacting some key points from the blog post

- _data/testimonials.yml
added testimonial from Dave Coombs
> added testimonial from Dave Coombs

- content/partners.md
> Remove </br>s

- content/about.md
Aim of the change is to highlight my experience:
- running teams
- coaching and mentoring teams including cultural change & transformation
- delivering business value
> New title and profile.

- content/about.md
Publishing my changes from #155 to master
> @mngau's new title and profile

- content/testimonial/tabcorp-francis-marino.md
Checking what this looks like on develop
> Added new tabcorp testimonial for Baymax

- static/css/agency.css
> Add new tabcorp testimonial

- content/testimonial/iag-dave-coombes.md
- content/testimonial/tabcorp-francis-marino.md
Using the right spelling of Dave Coombes
> Using the right spelling of Dave Coombes

- layouts/index.html
- layouts/partials/footer.html
- layouts/partials/slaask.html
I was unable to test the widget out locally. When I spoke to Slaask support they said I have to make the changes to a 'live' url.
Given I'm not sure whether the code snippet should be in the footer partial or in each page, I've put it into the Footer partial for now.
> Slaask trial experiment

- layouts/404.html
- layouts/about/single.html
- layouts/case-study/list.html
- layouts/cloud/single.html
- layouts/devops/single.html
- layouts/engineering/single.html
- layouts/index.html
- layouts/partials/js.html
- layouts/partners/single.html
- layouts/post/single.html
- layouts/taxonomy/case_category.html
- layouts/taxonomy/category.html
- layouts/taxonomy/tag.html
- layouts/taxonomy/testimonial_category.html
- layouts/testimonial/list.html
Add slaask partial to js partial so it appears in all pages.
Removed slaask include from individual pages.
> Slaask trial experiment updated

- content/about.md
> Update website copy 'about'

- static/js/cevo.js
> Open modal if it is specified in location

- layouts/partials/head.html
- layouts/post/single.html
this should help the social networks display the content appropriately.
> Open graph blog meta tags

- config.yaml
- content/legal/privacy-policy.md
- content/legal/terms-of-use.md
- layouts/legal/single.html
- layouts/partials/footer.html
Fixes #245, as requested by @SianHughes
> Legal pages
